# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.DeleteModel(
            name='FamilyInfo',
        ),
    ]
