# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20160414_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bloodgroup',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dateofbirth',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
